package Main;

import database.MazeDB;

import javax.swing.*;
import javax.swing.border.Border;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class HomePage implements ActionListener{
    JButton createMaze = new JButton();
    JButton createChildrensMaze = new JButton();
    JButton viewMazes = new JButton();
    JButton signOut = new JButton();
    JFrame frame = new JFrame();

    HomePage(){


        createMaze.setBounds(100, 250, 300, 50);
        createMaze.setText("Create Automatically Generated Maze");
        createMaze.setFocusable(false);
        createMaze.setFont(new Font("DM Sans",Font.BOLD,12));
        createMaze.setForeground(Color.WHITE);
        createMaze.setBackground(Color.RED);
        createMaze.addActionListener(this);


        createChildrensMaze.setBounds(100, 325, 200, 50);
        createChildrensMaze.setText("Create Childrens Maze");
        createChildrensMaze.setFocusable(false);
        createChildrensMaze.setFont(new Font("DM Sans",Font.BOLD,12));
        createChildrensMaze.setForeground(Color.WHITE);
        createChildrensMaze.setBackground(Color.RED);
        createChildrensMaze.addActionListener(this);


        viewMazes.setBounds(100, 400, 200, 50);
        viewMazes.setText("View Existing Mazes");
        viewMazes.setFocusable(false);
        viewMazes.setFont(new Font("DM Sans",Font.BOLD,12));
        viewMazes.setForeground(Color.WHITE);
        viewMazes.setBackground(Color.RED);
        viewMazes.addActionListener(this);


        signOut.setBounds(100, 475, 100, 50);
        signOut.setText("Exit");
        signOut.setFocusable(false);
        signOut.setFont(new Font("DM Sans",Font.BOLD,12));
        signOut.setForeground(Color.WHITE);
        signOut.setBackground(Color.RED);
        signOut.addActionListener(this);

        JLabel title = new JLabel();
        title.setText("Maze Generator"); //creates label for main login screen
        title.setHorizontalAlignment(JLabel.LEFT);
        title.setVerticalAlignment(JLabel.TOP);
        title.setForeground(new Color(0xCF2A27));
        title.setFont(new Font("DM Sans",Font.BOLD,72));
        title.setBounds(100, 100, 1000, 250);


        frame.setSize(1225,1000);
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.setLayout(null);
        frame.setVisible(true);
        frame.setTitle("Maze Generator");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Exits completely on application
        ImageIcon image = new ImageIcon("qut logo.png");
        frame.setIconImage(image.getImage());
        frame.getContentPane().setBackground(new Color(162,196,201));
        frame.add(title);
        frame.add(createMaze);
        frame.add(createChildrensMaze);
        frame.add(viewMazes);
        frame.add(signOut);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==createMaze) {
            frame.dispose();
            AutoGeneratedMaze autoMaze = new AutoGeneratedMaze();

        }
        if(e.getSource()==createChildrensMaze) {
            frame.dispose();
            ChildrensMazeGenerator childMaze = new ChildrensMazeGenerator();

        }

        if(e.getSource()==viewMazes) {
            MazeDB.main(null);

        }

        if(e.getSource()==signOut) {
            frame.dispose();
        }


    }
}
